### ISSUE TITLE
Error thrown when contract name starts with `I`

### ISSUE THREAD

**Issue by elenadimitrova** [duaraghav8/Solium#25] opened 2016-08-31 12:01 UTC
```
An error occured while running the linter on /Users/Elena/colonyDapp/truffle/contracts/IMyFactory.sol:
Error: null is not a valid AST node
An error occured while running the linter on /Users/Elena/colonyDapp/truffle/contracts/IMyResolver.sol:
Error: null is not a valid AST node
```

**Comment by duaraghav8** [comment] 2016-08-31 12:16
Could you paste the contract declaration code here?

Also, I'm slightly confused. By the asterisk ```*``` after ```I```, do you mean the contract name consists of any character following ```I``` (as in Regular expressions) or literally an asterisk (like ```I*```)?

**Comment by elenadimitrova** [comment] 2016-08-31 15:11
On your first question, below is a sample of the simplest of 3 contracts this error appears
```
contract IUpgradable {
  function upgrade(address newAddress);
}
```

For your second question I meant the asterisk as a regex, I updated the issue title to make this clearer.
tbh I couldn't find anything else common between the 3 contracts this throws on, besides their names starting with **I**

**Comment by duaraghav8** [comment] 2016-08-31 15:43
Just finished digging.
The problem was being caused by Abstract Functions (```upgrade``` for example).

I'm guessing its a coincidence that all your abstract functions lie inside contracts whose names start with 'I'!!

I've fixed this, will notify you when I make the new release.
Thanks :)

**Comment by elenadimitrova** [comment] 2016-09-01 09:46
Indeed, we declare all our abstractions in _interface_ contracts that we prefix with ' I '
Thanks for all the fixes. We rolled out the ones done so far and all is good! :)

**Comment by duaraghav8** [comment] 2016-09-01 11:05
ah! of course, makes more sense now
I'm glad you find it useful!

Also, **0.1.15** solves this, so closing.

**Closed by duaraghav8** 2016-09-01 11:05 UTC
